title: fruit-salad
hero_image: images/banner.png
description: fruit-salad description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Stamping
  - title: Change the fruit
  - title: Add resize buttons
  - title: Rotate the fruit
  - title: What's next?
  
