title: Fruit salad
hero_image: images/fruitsalad-banner.png
description: Create an app to make a fruit salad out of fruit of varying sizes and in different arrangements
version: 5
listed: true
copyedit: true
last_tested: "2020-09-01"
steps:
  - title: Introduction
  - title: Stamp fruit
  - title: Choose other fruit
  - title: Add a Grow button
  - title: Add a Shrink button
  - title: Add a Rotate button
  - title: What next?
  
