title: fruit-salad
hero_image: images/banner.png
description: Create an interface to concoct a fruit salad from fruit of varying sizes and in diffrent arrangements
version: 4
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Stamping
  - title: Change the fruit
  - title: Add resize buttons
  - title: Rotate the fruit
  - title: What next?
  
